services:
  app:
    image: ghcr.io/amiller/devproof-toy@sha256:c99245145521a0f9e416f67430a46a376fcd836d4cfddf8c100a2a875263e6ed
    ports:
      - "8080:8080"
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
      - store-data:/data
volumes:
  store-data:
